#include <SFML/Graphics.hpp>
#include <iostream>
#include <algorithm>
#include <cmath>
#include <chrono>
#include <thread>
#include "PlayerBar.hpp"
#include "Ball.hpp"
#include "GameStates.hpp"
#include "MenuText.hpp"
